### ISSUE TITLE
Laravel Version

### ISSUE THREAD

**Issue by daniyalishaq** [webparking/laravel-clio#1]
Is it not compatible with laravel 8? I've laravel 8 installs and it gives me this error while installing the package.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires webparking/laravel-clio 1.0 -> satisfiable by webparking/laravel-clio[1.0.0].
    - webparking/laravel-clio 1.0.0 requires laravel/framework ^5.5||^6||^7 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.12).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by remkobrenters** [comment]
Will update this today as it is compatible.

**Comment by remkobrenters** [comment]
Done. Can you verify it works as expected.

**Comment by daniyalishaq** [comment]
Thank you. It's working now.
